### ISSUE TITLE
Please check the following error when running the example code for the first time

### ISSUE THREAD

**Issue by waynewccheng** [plemaillet/wsi#1]
Error using save
Cannot create 'XYZ_array.mat' because
'C:\Users\wcc\Documents\GitHub\wsi\code_read_spectral_data\output\Bladder_red\CIE_Coord'
does not exist.

Error in ExampleCode (line 54)
save([pwd '\output\Bladder_red\CIE_Coord\XYZ_array'],'XYZ_array');

**Comment by plemaillet** [comment]
Yes, there was a typo in the folder name, I named it "ouput" instead of "output"
It should work now
