### ISSUE TITLE
Separate light source from transmittance

### ISSUE THREAD

**Issue by waynewccheng** [plemaillet/wsi#3]
https://github.com/plemaillet/wsi/blob/f4bc4c3a2b2a02bb4ede88876f18659a9ce213b0/code_read_spectral_data/%40ReadSpectralDatabase/ReadSpectralDatabase.m#L21

This class is about spectral transmittance, which should be independent of the light source. The light source should not be a property of this class. For example, how do we use D50 as the light source?

**Comment by plemaillet** [comment]
Done
