### ISSUE TITLE
XYZ2sRGB

### ISSUE THREAD

**Issue by waynewccheng** [plemaillet/wsi#4]
https://github.com/plemaillet/wsi/blob/f4bc4c3a2b2a02bb4ede88876f18659a9ce213b0/code_read_spectral_data/%40ReadSpectralDatabase/ReadSpectralDatabase.m#L373

By the name of this function, it seems to convert XYZ to sRGB. How is XYZ involved in this function?

**Comment by plemaillet** [comment]
Called by new function transmittance2sRGB which first call transmittance2XYZ to change the object properties XYZ (and CovXYZ). XYZ2sRGB uses obj.XYZ as an input.
