### ISSUE TITLE
Reshape

### ISSUE THREAD

**Issue by waynewccheng** [plemaillet/wsi#6]
https://github.com/plemaillet/wsi/blob/f4bc4c3a2b2a02bb4ede88876f18659a9ce213b0/code_read_spectral_data/%40ReadSpectralDatabase/ReadSpectralDatabase.m#L396

This function is purely reshape and has nothing to do with sRGB vs. TIFF conversion. Also, this function may not be needed.

**Comment by plemaillet** [comment]
Ok, done
